### ISSUE TITLE
 PHP 7 Compatibility

### ISSUE THREAD

**Issue by Zodiac1978** [elmastudio/yoko#1]
FILE: /wp-content/themes/yoko/functions.php
————————————————————————————————–
FOUND 1 ERROR AFFECTING 1 LINE
————————————————————————————————–
402 | ERROR | Use of deprecated PHP4 style class constructor is not supported since PHP 7
————————————————————————————————–

**Comment by ellenbauer** [comment]
fixed in v1.2.3
