### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by Zodiac1978** [elmastudio/yoko#2]
`create_funtion`  is deprecated since PHP 7.2: http://php.net/manual/de/function.create-function.php
Used in https://github.com/elmastudio/yoko/blob/e91b444fe732c5298dca31539813a3d647bd4f14/functions.php

**Comment by ellenbauer** [comment]
Thanks so much for your help, fixed this in the recent 1.2.3 update.
